### ISSUE TITLE
Firefox last not firing in scroll event

### ISSUE THREAD

**Issue by Maggieryder** [react-spring/react-use-gesture#100]
Have an issue where I'm trying to lock scroll axis. Based on your solution for locking axis during Drag event, and being fairly new to this, the only way I could find to do this was by changing overflow-x or overflow-y styling attribute once direction had been determined and reverting them on the 'last' event. It's working fine in safari, chrome etc, but 'last' does not seem to be firing in Firefox, and worse, the  activity continues even after page reload, so I can't get the loop to stop. This may be a bug, but would also suggest that you implement disabling scrollX or scrollY behavior dynamically on the fly somehow so that this would be much easier. 
Please excuse my inexperience if there is an obvious solution.

**Comment by dbismut** [comment]
Hi Maggie, do you mind creating a sandbox with your latest attempt? This will be easier to settle for me.

**Comment by Maggieryder** [comment]
Hi dbismut,
Thanks for getting back to me so quickly. 
Your codebase is working as expected as I just removed my dynamic overscollX/Y styling and the 'last' event is firing fine in Firefox. 
But that leaves me unresolved as to how to locking scrolling in only one direction depending on the first move being more x than y (or vice-versa). Any help would be much appreciated.

**Comment by dbismut** [comment]
I’m on the move at the moment, but I guess you tried replacing useDrag with useScroll or useWheel in the lock axis example. My guess is that since wheel or scroll are debounced you might not get the result you want (ie you might think last is fired too late), but I’d appreciate if you could describe what doesn’t work for you.

**Comment by Maggieryder** [comment]
Yes, iPad/tablet is ultimate goal, but desktop should work too. 
Not the body dom node, it's an internal node with some complex interaction - you can dynamically add width and height by adding horizontally and vertically aligned elements independently, but if you start scrolling, it's gets really messy if you are able to scroll on both axes at the same time. Hope this explains well

**Comment by dbismut** [comment]
Ok so this is me thinking out loud from the top of my head and I’m usually really bad at this but I’ll try. So there’s one option that would using drag interaction to fake the scroll. In that case you might have some additional work if you want to emulate Safari’s but that’s doable. Of course that won’t work using the mouse wheel so that might not work for you. 

If you want to use scroll, then using overflow-x/y would be my initial thought, otherwise maybe preventing default on scroll events and faking scroll yourself (ie el.scrollTo)?

**Comment by Maggieryder** [comment]
I'd go for the second option but can't get rid of the "Unable to preventDefault inside passive event listener invocation" error even when I drop the spread on the component and add listener as described in useEffect(bind, [bind]) with domTarget.

**Comment by dbismut** [comment]
That’s explained in the FAQ, you need to pass `{ event: { passive: false }}` in the config object.

**Comment by Maggieryder** [comment]
I did that... but I see now I was doing it wrong!!! Think I can handle it from here. Let me know if you ever implement a lockYAxis or LockXAxis only flag that can be added dynamically on the fly - something like: event.lockYAxis = false
Thanks for your help. You're a dream to work with!!!

**Comment by dbismut** [comment]
Glad I could help! Closing this but let me know if this works out for you eventually.
