### ISSUE TITLE
Prevent scroll when dragging on mobile/tablet.

### ISSUE THREAD

**Issue by adamhaeger** [react-spring/react-use-gesture#101]
Is there any way to prevent the page from scrolling when using a drag n drop gesture on tablet/mobile?

I am implementing drag and drop similar to your dnd example (https://codesandbox.io/s/draggable-list-vp020), and the example also scrolls up and down when moving items on tablet.

**Comment by dbismut** [comment]
That really depends on your use case, it’s not directly linked to the use of this library. As soon as I have some time I’ll check if there is a scrolling issue with the example, but I’m not experiencing any on my iPhone. In any case, if you don’t want the body to respond to scroll you should probably prevent default on all touch events (and please read the FAQ about passive events to understand how to do so (tldr: use `{ domTarget: yourRef, event: { passive: false }}` config option, and make sure you don’t prevent default the last event as it’s debounced).

**Comment by impulse** [comment]
The easiest solution I have found is to use `style={{ touchAction: 'none' }}` on your `animated.div`.

Here is an example: https://tailwind-slidecards.netlify.com/

**Comment by dbismut** [comment]
@impulse that actually looks like a way better option!

**Comment by adamhaeger** [comment]
Thanks @impulse , I've tried that as well but it didn't work in my case.
So I've ended up doing this which works fine:

`const bind = useGesture(
    ({ down, delta, xy }) => {
      if (down) {
        // Prevent scroll on touch screens while dragging:
        document.ontouchmove = function(e) {
          e.preventDefault();
        };
      } else {
        document.ontouchmove = function() {
          return true;
        };
      }
    }}
  );`

Don't love the solution but it works for now.

**Comment by dbismut** [comment]
@adamhaeger Any solution that works is fine I guess! You might want to use `addEventListener` instead?

To expand a bit more on my previous explanation, you might want to h ave a look at this sandbox: https://codesandbox.io/s/react-use-gesture-simple-prevent-scroll-p7cjf

Unfortunately, using refs is incompatible with the idea of passing an argument to `bind`, which ruins the purpose of the draggable-list implementation, but I found @impulse implementation to be working perfectly.

Otherwise you may want to have a look at [body-scroll-lock package](https://github.com/willmcpo/body-scroll-lock).

**Comment by dotlouis** [comment]
Just adding my two cents for anyone looking for a solution.

`touch-action` changes won't be taken into account if the `drag`/`touchmove` gesture has already started. [See the yellow box in the doc](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)

It's probably why @adamhaeger could not use it. It seems you wanted to change your element's `touch-action` to `none` when the user had the finger down and back again when the user releases it.
It's unfortunately not possible as of the time of my writing. There is a discussion about this topic here: https://github.com/w3c/pointerevents/issues/178, although it does not seem very active.

Regarding the interception and prevention of default scrolling behavior, keep in mind that moderns browsers are defaulting to passive event listeners which can't be canceled ([because performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention))
So you may want to use this instead:
```JS
addEventListener('touchmove', e => e.preventDefault(), {passive: false})
```

Here is a simple hook I made if it can help:
```JS
function usePreventScroll(preventScrollRef) {
  useEffect(() => {
    const preventScrolling = e => {
      if (preventScrollRef.current) {
        e.preventDefault()
      }
    }

    document.addEventListener('touchmove', preventScrolling, {
      passive: false,
    })
    return () => document.removeEventListener('touchmove', preventScrolling)
  }, [])
}
```

Which you can then use like so:
```JS
const preventScrollRef = useRef(false)
usePreventScroll(preventScrollRef)
useGesture({
onDrag: ({down}) => {
  if(down) {
    preventScrollRef.current = true
  } else {
    preventScrollRef.current = false
  }
}});
```

**Comment by dbismut** [comment]
Hey @dotlouis indeed. In regards to your hook, I think this is pretty much what body-scroll-lock does if I’m not mistaken!

**Comment by frozar** [comment]
Just for information, now there's also an extra documentation page on React UseGesture site which gives some tricks to handle this behavior:
https://use-gesture.netlify.app/docs/extras/

**Comment by FRMR1** [comment]
@dotlouis Nice one, that works well. Thanks.
