### ISSUE TITLE
useDrag on mobile safari with pointerEvents set to true

### ISSUE THREAD

**Issue by goldbuick** [react-spring/react-use-gesture#103]
https://codesandbox.io/embed/react-three-fiber-gestures-dh2jc

I am going to start looking into why this isn't working on iOS 13.1.3
PEP no longer polyfills on iOS, their pointer event examples seem to work fine on the phone
However the linked react three fiber example does not?

I am kind of stuck here because react three fiber requires pointerEvents

**Comment by dbismut** [comment]
Hi @goldbuick, isn't this more of a PEP issue? This lib will never polypill pointer events I'm sorry...

**Comment by goldbuick** [comment]
So PEP no longer does polyfill on iOS 13.x because pointer events are now native to the browser.

However that being said with the native pointer events on iOS useDrag isn't working. So please don't mark this as invalid.

**Comment by dbismut** [comment]
@goldbuick ok I'll reopen the issue for the sake of investigation. The linked sandbox seems to work normally on my phone (running 13.2 beta) but doesn't on my friend's phone running (13.1).

From [Can I Use](https://caniuse.com/#feat=pointer), it looks like there's an issue with the value of the `buttons` property:

> Value of pointerevent.buttons is incorrect on pointermove events generated by touches. Is 0 but should be 1.

In the lib code, there's these lines which involve checking on the `buttons` value to make sure the drag is still active when moving the pointer:

https://github.com/react-spring/react-use-gesture/blob/43377e12b5e4796076b32f8c9cdadb788883275a/src/recognizers/DragRecognizer.ts#L77-L80

You might think starting the gesture on `pointerdown` and stopping it on `pointerup` would suffice, but this is useful in situations where the pointer exits the document (ie you click and start dragging, then your mouse goes off the window, you release the mouse out of the window and come back in, you would expect the drag gesture to end. If it wasn't for the check on `pointermove`, the gesture would continue since the `pointerup` event hasn't been registered.

This *might* explain why the bug on 13.1 ruins it, I'll run some tests on my side, but in the meantime I don't know if waiting for iOS 13.2 to be out or installing the beta is an option for you.

PS: to be honest I didn't know PE were now native on iOS 13, this is great news, as it means we might drop legacy events at sone point.

**Comment by goldbuick** [comment]
I am perfectly okay waiting for 13.2 this is for a personal project!

Thank you so much for checking, and yes being able to drop the legacy events would be pretty nice!

This is what I was working on last night when I discovered the issue when trying from my phone.
https://www.twitch.tv/videos/498304469

**Comment by dbismut** [comment]
Oh wow this is really cool! @drcmda you might want to check this ;)

**Comment by dbismut** [comment]
(updated my previous message, the lines are indeed what prevents 13.1 from working correctly). I'll leave this open until 13.2 comes out.

**Comment by goldbuick** [comment]
iOS 13.2 is out now! Tried the sandbox and it’s working ❤️ I’m really happy to have this

**Comment by dbismut** [comment]
That’s great news. Just so you know I’ve stumbled upon a bug related to Pointer Events that I’ve reported to the WebKit team: 

https://bugs.webkit.org/show_bug.cgi?id=203364

I don’t think it will affect you since you’re using the canvas though!
