### ISSUE TITLE
Thoughts 

### ISSUE THREAD

**Issue by aholachek** [react-spring/react-use-gesture#109]
Hi @dbismut,

Here's a list of thoughts I had after working on the react conf talk. Most of them involve making it easier to implement gesture animation, but part of the charm of this library for me is how flexible it is, it really lets you handle the gestures as you see fit, and I never had to fight with it to do something custom. So maybe just documenting some patterns or exposing some helper functions could be beneficial?

1. Although I think the `react-use-gesture` examples generally use springs for animation during gesture, it seemed to me while I was investigating best practices that during the gesture the movement should be direct manipulation, at least on mobile. However, the velocity args provided by the `react-use-gesture` hooks could not be simply loaded into the spring provided by react-spring, as I initially thought, since the velocity argument in `react-spring` seems to represent a different type of value than px/ms. I had to work around this by [creating a wrapped `useSpring` hook](https://github.com/aholachek/mobile-first-animation/blob/master/src/useVelocityTrackedSpring.js) that tracked gesture velocity, which I could then send in to the final spring animation. This was probably the biggest source of confusion I had.

2. One pattern I used quite a lot was a guard like this at the very top of the `useDrag` handler:

```js
  if (!memo) {
        const isIntentionalGesture =
          Math.abs(movementX) > threshold &&
          Math.abs(movementX) > Math.abs(movementY)

        if (!isIntentionalGesture) {
          if (!willTransform) setWillTransform(true)
          return
        }
        memo = x.value - movementX
      }
```

Basically waiting for some threshold (hysteresis) to be set, and then [initiating memo with the spring value minus the threshold difference](https://github.com/aholachek/mobile-first-animation/blob/master/src/EmailList/ListItem.js#L72). And optionally setting `willTransform` on the element in advance, instead of indiscriminately using the `translate3d` hack, (although I can't say that I personally found evidence that there was a specific performance benefit to doing it that way, that is what [seems to be recommended](https://dev.opera.com/articles/css-will-change-property/).)

3. I hunted around the internet for some best practices in implementing the animations, e.g. the `projection` and `rubberbanding` formulas I mentioned in the talk, and [made a small utility file of the ones I found most helpful](https://github.com/aholachek/mobile-first-animation/blob/master/src/utilities.js). Having them readily available would have been cool.

4. Another pattern I found myself repeating was trying to filter out [click events in the onDrag handler](https://github.com/aholachek/mobile-first-animation/blob/master/src/MusicDrawer/index.js#L91), I felt the way I did it was hacky and maybe there could have been a better way. I know `react-use-gesture` has a `dragDelay` but in general I want to filter based on gesture distance not duration. I think framer motion has a [separate tap handler](https://www.framer.com/api/motion/gestures/#tap) and something like that would be helpful, especially for the common pattern on mobile of animating on tap (e.g. examples #1 and #2 in [this article](https://medium.com/@nathangitter/building-fluid-interfaces-ios-swift-9732bb934bf5)).

5.  I know this isn't the responsibility of the library, but some documentation on touch-action / touch cancellation might be helpful, (I definitely did appreciate the documentation on how to add a cancelable touch handler if necessary!) because it's so important and such an easy thing to miss when you're just starting out.

6. This is more of a `react-spring` thing, but just to bring it up: I really wish we could use `frequency response` / `damping ratio` to tune springs in react-spring instead of stiffness / damping, it's so so much easier!

7. I found some of the provided examples to perform poorly on mobile (e.g. the bottom drawer). It might be nice to categorize examples as `desktop` and `mobile` optimized, or something like that.

Thank you again for working on this library!!  Please let me know if there's any way I can be helpful.

**Comment by dbismut** [comment]
Hi @aholachek 

First of all massive thanks for exposing the lib during the React conf and for the insightful feedback. Here are some initial thoughts, I'll probably need some more time to dig into all of your points.

### 1. Velocity

You're absolutely right, I ran into the same issue.

My understanding was that `react-use-gesture` calculates pixels per _millisecond_ (which seems to be the standard) when `react-spring` relies on pixels per _second_. Also, while `react-spring` does calculate velocity for spring animations, it doesn't for decay or easing. `react-spring` v9 should fix all of this.

[Here is a proof of concept](https://codesandbox.io/s/spring-inertia-latest-oo3mi) of decay with bounce off limits in v9. It's far from perfect (I'm missing the rubber band effect when manually trying to drag off bounds), but you should get the idea if you _throw_ the pink square up or down (I wish there was a native option to do this in `react-spring` @aleclarson 👀, `popmotion` has it after all!).

You can see that velocities are passed around from `react-use-gesture` to `react-spring` and everything seems to work properly. Prior to the canary version of v9 I had to manually calculate velocity for decay and multiply the `velocity` by `1000` to make it work properly.

### 2. Detecting intentional drag gesture

You're right, this is definitely useful for `drag`. Currently `react-use-gesture` uses the same config object for all gestures, but `drag` should have its own set of configurable options. I've already included one to distinguish `drag` from `clicks` but having a separate option object for `drag` would allow to implement more out of the box features for `drag` (I understand this is not enough from reading through your issue ^^) .

Btw, are there any benefits in dynamically setting `will-change: transform` rather than having it set once and for all?

### 3. Utility functions

I'll have a look at all of them. `clamp` or `range` do make sense (although `react-spring` already have a `to` interpolation function that achieves what `range` does).


### 4. Filtering out clicks

I'll try to work out something. Maybe we could have something like:

```jsx
useDrag(({ isIntentional, isTap }) => { ... }, {
  intentionThreshold: 10, // isIntentional would be set to true when threshold is reached
  tapThreshold: 3 // isTap will be true if total movement is inferior to the threshold
})
```

### 5. touch-action

To be honest I discovered `touch-action` a few hours prior to watching your conf, someone mentioned it in one of the issues. I need to run through examples to see where it applies but it's definitely a great way to prevent unwanted browser native behavior and worth mentioning.

You're definitely right about expanding documentation about touch cancellation.

### 6. Spring interface through damping ratio / frequency

I think this should be already the case in latest `react-spring` canary @aleclarson @drcmda ;)

### 7. Examples performing poorly on mobile

I guess I'll just have to buy an old Samsung as you suggest in your talk 😅

I think the drawer example performs so poorly because of the dynamic blur it applies on the background. It works fine on my iPhone X but I totally see why it wouldn't on older pones. I'll change the example with less demanding animations, you'll tell me how it goes! 

### Conclusion

Well that's really cool, I think there's quite a few things we could improve in v7, I'll try to fix a roadmap sometime next week. Thanks again for your time on this, this is much appreciated!

**Comment by aleclarson** [comment]
> I wish there was a hook or a config to do this in `react-spring` @aleclarson 👀, `popmotion` has it after all!

Not sure what you mean here. You want `react-spring` to provide a rubberband effect?

> Prior to the canary version of v9 I had to manually calculate velocity for decay and multiply the `velocity` by `1000` to make it work properly.

> 4\. This is more of a `react-spring` thing, but just to bring it up: I really wish we could use `frequency response` / `damping ratio` to tune springs in react-spring instead of stiffness / damping, it's so so much easier!

If you're not using `useTransition`, you should be able to install [the latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404) without any code changes. 

As @dbismut said, it fixes the velocity issue and exposes `config.frequency` and `config.damping` for "frequency response" and "damping ratio". The `config.damping` defaults to 1, which is "no bouncing".

**Comment by dbismut** [comment]
> Not sure what you mean here. You want react-spring to provide a rubberband effect?

@aleclarson Sorry I realize I wasn't clear, and maybe we should move this to `react-spring`! It's slightly more complex than rubberband, as it would work with decay: whenever the decayed value goes off bounds, it starts a reverse spring movement to the nearest bound with an initial momentum. This is very similar to what happens on iOS when you scroll off bounds with inertia.

That would mean adding bounds + some other config options to the config object. I can probably try to make a PR for this if you think it's useful.

**Comment by aholachek** [comment]
Hi @aleclarson,

Quick follow up question: in my experience, frequency response is a number between about 0.1 - 1.5, as seen [here in this apple talk](https://developer.apple.com/videos/play/wwdc2018/803/?time=2115). I think it's also true in equations [like this one](https://gist.github.com/jenox/7ccbb414b8697ceec9463892b2e65162#file-uispringtimingparameters-convenience-swift). 

However, with the current react-spring canary, I needed to crank the `response` variable [up to about 10](https://codesandbox.io/s/spring-inertia-latest-t1yph) to get an animation with reasonable speed. Unlike the `frequency response` I'm used to, increasing the number increases the speed of the spring rather than decreasing the speed . 

Was this a design decision? To be honest, I only know of frequency response/ damping ratio from material put out by apple so maybe there are multiple ways to do it and I only know of the iOS way?

**Comment by drcmda** [comment]
As for the CSS blur, sadly it's being rendered on the CPU on many devices, i believe even some desktop browsers like Firefox. It is completely useless at this point unless it's for static backdrops or Chrome only/newer devices.

**Comment by dbismut** [comment]
@aholachek Hey Alex, I've just released alpha for v7 (`7.0.0-alpha.5`) that only implements `useDrag`.

You'll find a sandbox here: https://codesandbox.io/s/react-use-gesture-v7-oft72

| State | Type | Description |
| ------ | ----- | ----- |
| click | `boolean` | `click` will be `true` when the total displacement is inferior to `3`.  |
| swipe | `[number, number]` | `swipe[0]` will be `-1 \| 0 \| 1` for `swipeLeft \| no swipe \| swipeRight`. Note that `swipe` is calculated on drag end (so only when the finger is released). |

`drag` now has the following config properties:

| Config | Default | Description |
| ------ | ----- | ----- |
| `intentionalThreshold` | `undefined` | Accepts `number \| [number, number]`. When set, the drag handler will only fire when the movement is intentional in either one of the directions. If you set `intentionalThreshold: 100`, and you move horizontally to the right, handler will fire when your horizontal displacement is superior to `100`. Although you'll be able to freely control the displacement horizontally once the threshold is reached, you need to breach the vertical threshold so that `movement` and `offset` actually respond to changes. |
| `filterClicks` | `false` | `filterClicks: true` sets `intentionalThreshold` to `[3, 3]` when not defined by the user, but will still fire the drag handler with `click: true` if the threshold hasn't been breached. |
| `swipeVelocity` | `0.5` |  Accepts `number \| [number, number]`.


I could also add a direction lock to achieve the same logic as [this sandbox](https://codesandbox.io/s/25n4m933j).

Some of the above might feel a bit circumvoluted and I'd be happy to explain the design choices. Overall, I think this should feel natural to the end user.

Let me know what you think and if this helps simplifies your implementation logic!

**Comment by aholachek** [comment]
Nice, thank you @dbismut . I'm going to refactor my code examples from my talk with this alpha version and get back to you this weekend with any additional feedback. I think `intentionalThreshold` and `filterClicks` are going to be very helpful.

**Comment by dbismut** [comment]
@aholachek I've just added `axis` in `7.0.0-alpha-9` that can accept `'x'` or `'y'` (or `undefined`). If you set `axis: 'x'`, the hook will prevent the handler from firing if the movement is intentional and if the displacement on the `y` axis is **once** superior to the displacement on the `x` axis. This is similar to your check but it cancels the gesture as soon as an unwanted gesture is detected.

**Comment by codynova** [comment]
> I've just released alpha for v7 (`7.0.0-alpha.5`) that only implements `useDrag`.

@dbismut This is awesome. Any chance we can get dragDelay added somehow? Maybe even changing prop names like `intentionalDistanceThreshold` and `intentionalDurationThreshold` or whatever makes most sense

**Comment by dbismut** [comment]
@codynova It is already in there, it’s just renamed `delay`.

Essentially the `useGesture` hook (not yet in alpha v7), will have a config object like so:

```js
{
  domTarget,
  eventOptions,
  /*...*/ 
  drag: {
    delay,
    axis,
    intentionalThreshold,
    /*...*/
  }, 
  wheel: { /*...*/ },
  scroll: { /*...*/ },
  /*...*/
}
```

However, each specific gesture hook flattens it’s config options so `useDrag` config object would look like:

```js
{ domTarget, eventOptions, delay, axis, /*...*/ }
```

Makes sense?

**Comment by aholachek** [comment]
I tried adding the following options to a demo:
```js
 {
      axis: 'x',
      filterClicks: true,
      threshold: 15
    }
```
`filterClicks` works great and is super useful. I think the `axis` option is getting ignored, though, and `threshold` prevents the animation from ever getting triggered.

(I'm using version `7.0.0-alpha.14`.)

**Comment by dbismut** [comment]
Hi @aholachek, thanks for giving it a shot. That’s weird, I’m using the same settings in the [sandbox](https://codesandbox.io/s/react-use-gesture-v7-oft72) and it seems to work ok. 

What device are you testing this on? Is there any chance you could open a repro sandbox? Thanks a lot!

**Comment by dbismut** [comment]
@aholachek I've just released `7.0.0-alpha.15` which should fix some peripheral important bugs. I don't know if it actually fixes your problem since I wasn't able to reproduce it, but you might give it a chance. Also `lockDirection` is a new config option that locks the gesture axis based on the initial direction of the gesture.

**Comment by aholachek** [comment]
Hi @dbismut,
I just realized that one of the issues I was seeing was due to using the new react-spring api and not fully updating my code. It looks great now that I've fixed it, the new helper methods allow for more concise code on my end.

One thing I'm trying to figure out is the cleanest way to deal with the threshold offset. 

Before, I would wait until the threshold was passed, then [cache it in memo](https://github.com/aholachek/mobile-first-animation/blob/master/src/EmailList/ListItem.js#L81) like: 
```js
  memo = x.value - movementX
```

Now that I have threshold, I can simplify that logic, but I don't understand how to add the threshold offset to get a smooth animation once the threshold is met. I'm probably missing something obvious. I thought I could do something like 
` const cachedMovement = memo + offset[0] > 0 ? -threshold : threshold` but that doesn't seem to be working.

[Here's the sandbox](https://codesandbox.io/s/github/aholachek/mobile-first-animation/tree/react-use-gesture-alpha-test) (the relevant file is in `src/EmailList/ListItem.js`, and the example of the ui "jump" is [here in the demo](https://wtn0g.csb.app/email-list).

One more thing that might be helpful (although it might also bloat the library so feel free to ignore this) is adding a "rubberbandedMovement" variable, with the option to specify min and max thresholds, so that I could totally get rid of that logic as well. When combined with the other features you've added, that would get rid of a lot of the boilerplate in each animation demo.

**Comment by aleclarson** [comment]
> Quick follow up question: in my experience, frequency response is a number between about 0.1 - 1.5, as seen [here in this apple talk](https://developer.apple.com/videos/play/wwdc2018/803/?time=2115). I think it's also true in equations [like this one](https://gist.github.com/jenox/7ccbb414b8697ceec9463892b2e65162#file-uispringtimingparameters-convenience-swift).
> 
> However, with the current react-spring canary, I needed to crank the `response` variable [up to about 10](https://codesandbox.io/s/spring-inertia-latest-t1yph) to get an animation with reasonable speed. Unlike the `frequency response` I'm used to, increasing the number increases the speed of the spring rather than decreasing the speed .
> 
> Was this a design decision? To be honest, I only know of frequency response/ damping ratio from material put out by apple so maybe there are multiple ways to do it and I only know of the iOS way?

Definitely not intended. I never got around to making a demo for `frequency`/`damping`, so I suspect it's [these lines](https://github.com/react-spring/react-spring/blob/4be2ac3fdcc46da4a564ad21a588dcbc57b1e6fb/packages/core/src/Animation.ts#L170-L173) causing the issue. Feel free to open a PR with a fix :)

**Comment by dbismut** [comment]
> Now that I have the threshold option, I can simplify that logic, but I don't understand how to add the threshold offset to get a smooth animation once the threshold is met. I'm probably missing something obvious.

Ok I think I know where this comes from: I thought it would be a good idea that the *first* value returned by `movement` would take into account the threshold, but it's actually stupid. In your case, your threshold is `30` and the first movement value you get is `30`. You could animate smoothly to it with `immediate: !first` but by the time the second frame comes, your value didn't have the time to animate to `30`.

I'll fix this so that the first `movement` value takes into account the threshold. I hope I can have it up in 15mn ;)

**Comment by dbismut** [comment]
@aholachek should be good in `7.0.0-alpha.18`. Have a look at:
https://codesandbox.io/s/mobile-animation-demos-s602y

I guess this is the behavior you wanted?

I'll investigate rubber banding :)

**Comment by aholachek** [comment]
Yes, it's working perfectly now. It's allowed me to simplify even further by not having to adjust `movementX` for the initial threshold.

**Comment by dbismut** [comment]
Hey @aholachek I've had a try at implementing rubber banding. So here is the api for config:

```js
{
  drag: {
    bounds: { top: 100, bottom: -100, left: -100, right: 100 },
    rubberband: true // rubberband coefficient, can be a number (default to 0.15)
  }
}
```

So both `movement` and `offset` will be returned both _bounded_ and _rubberbanded_. When you release the drag, if `movement` and `offset` are out of bounds, they will return to the closest bound.

You can play with this option here by activating the bounds in the GUI:
https://codesandbox.io/s/react-use-gesture-v7-oft72

Let me know if this helps!

**Comment by aholachek** [comment]
Hi, sorry for the delay in response, I’ve been trying to get my thoughts in order so that what  my questions make sense.

A common pattern is for developers to be dealing with flexible bounds for animations rather than fixed ones (since the size of touch devices varies so much). 

#### That results in a common flow like the following:

1. User touch begins 
2. Component immediately caches relevant component sizes by measuring the DOM (this will result in an updated `bounds` configuration) 
3. Period of no action for x seconds as threshold is reached 
4. Finally, threshold is reached and animation is triggered.

#### So, my questions boil down to asking about two main pieces of functionality:

1. It seems like if we use the `threshold` option, we can no longer do the immediate set up DOM measurement logic in step number 2. I thought maybe I could use the `onDragStart` handler to help with this but that is also affected by the threshold.
2. Right now, as far as I understand, that setup logic would have to `setState` and trigger a render in order to update the `bounds` argument. But on a less-powerful device, we probably want to avoid extraneous renders right as an animation is beginning. Is there a way around this? Can I dynamically update the settings passed into the options hash to `useGesture`?

I think pre-caching DOM sizes, e.g. on initial mount, would work in some cases, but it might lead to bugs when the cached sizes are outdated (say, if a user rotates a mobile device or the component changes its size in response to an update. Trying to listen to all events that might affect dom sizes seems like it could get complicated.

Does this make sense? (Maybe there is an obvious answer to get around all this that I am not considering.)

**Comment by dbismut** [comment]
Hi @aholachek, I’m no perf expert but I don’t think we should be worried about one additional render in that case. I know there’s a lot of press around minimizing render cycles but React is actually fast (and even faster in production mode).

I think the best way would be to use a hook such as `react-use/useWindowSize` or even `react-use/useMeasure` which would help us keep `bounds` in sync.

There would always be a way to avoid that render, which would probably involve refs and bounds to be a function but I don’t think it’s necessary tbh, but maybe thats me being lazy 🤗

**Comment by aholachek** [comment]
That makes sense! Regardless, it would be nice to be able to have both a `threshold` as well as an immediate callback for any setup logic (like adding the [`will-change:transform` css prop]((https://dev.opera.com/articles/css-will-change-property/)))

**Comment by dbismut** [comment]
I don't know how that callback would work I'm afraid. What you could do is have `willChange` as a property of a spring, so that setting it doesn't trigger a render. `react-spring` treats non interpolatable values immediately so I guess this should be ok?
