### ISSUE TITLE
useGesture's onClick has old value for props?

### ISSUE THREAD

**Issue by codynova** [react-spring/react-use-gesture#117]
I'm a bit confused by the behavior observed through console.logs in this codesandbox. I'd expect the value of `isEditMode` to be consistent throughout the app. Can you help me understand this behavior? Hopefully I'm not overlooking something super obvious.

https://codesandbox.io/s/draggable-list-ct10q

I think this may be a bug, as the same issue doesn't occur in a standard `onClick` handler.

**Comment by codynova** [comment]
I think this may be a bug, as the same issue doesn't occur in a standard `onClick` handler.

**Comment by dbismut** [comment]
@codynova good catch thanks! It is actually not so obvious, it was a closure bug which is a common error when using hooks, sorry about this! It's fixed in `7.0.0-alpha.30`. I will move `7.0.0` to beta state as soon as I finish the first draft of documentation, hopefully by end of week, but the current alpha should be relatively bug-free.

Please leave the issue open, I'll close it when `7.0.0` is mature for release of if I have time to fix version `6.0.14`.

**Comment by codynova** [comment]
@dbismut Awesome David, thanks for the great work and speedy resolution as always. 7.0.0-alpha.30 is looking great
