### ISSUE TITLE
The readme demo doesn't work w/ latest revs

### ISSUE THREAD

**Issue by geofflittle** [react-spring/react-use-gesture#122]
The demo in the readme doesn't work with current latest library revisions.

See this fork: https://codesandbox.io/s/react-use-gesture-simple-9tlw8

Using `react-spring` library revisions

```
react-spring: 8.0.27
react-use-gesture: 6.0.14
```

**Comment by dbismut** [comment]
Hi @geofflittle not sure I understand. Demos now use react-use-gesture 7.x and react-spring 9.x (canary build). The sandbox you link is using react-spring v8 and v8 doesn't support shorthand style attributes x / y / scale. You will need to do something like:

```jsx
import {interpolate} from 'react-spring'
<animated.div style={{
  transform: interpolate(
    [props.x, props.y, props.scale], (x,y,s) => `translate3d(${x}px,${y}px,0) scale(${s})`
  )
}} />
```

Closing this but feel free to expand if this isn't clear.

**Comment by geofflittle** [comment]
Hi @dbismut,

Thanks for taking the time.  I'm new to react-spring (and to react and node in general) so when I want to integrate `react-spring` and `react-use-spring` into my project I do

```
npm install react-spring react-use-gesture
```

Currently this command installs versions `8.0.27` and `6.0.14`, respectively.

Then to get started I copy the source from the demo into my project and run it only to find that it doesn't work.

I now understand that this is because the versions used in the demo are newer / are canary builds, but as someone new to integrating with the library, demos using these versions are not useful.

As a consumer of the library, I expect the demos to use the latest stable / currently published version that is downloaded via `npm install`.  These demos would be most useful to me.

Thanks again,
Geoff

![Screen Shot 2019-12-25 at 10 28 25](https://user-images.githubusercontent.com/3976777/71448478-f9588500-2701-11ea-884e-d711c7262ade.png)

P.S.: It's also confusing that there's a library called `react-with-gesture` (in contrast to `react-use-gesture`).  What is its use?

**Comment by dbismut** [comment]
Hi @geofflittle, thanks for pointing this out. I will amend the Readme later to be more explicit about the versions use. I’ll give the beta a few more days and will release a stable v7 of react use gesture.

Anyway, to be able to use react use gesture and react spring so that the examples work you should install the packages like so:

```
npm install react-use-gesture@beta react-spring@next
```

The reason why I use react spring v9 instead of v8 in examples is that v9 api is more convenient and allows more compact, less distracting code. I understand your frustration but v9 is just a few weeks away.

> P.S.: It's also confusing that there's a library called react-with-gesture (in contrast to react-use-gesture). What is its use?

Actually react-with-gesture is the old name for react-use-gesture and is not maintained anymore (we should probably make this more explicit). We decided to drop support for render props and focus on hooks as we believe they’re much more convenient. react-with-gesture was solely focused on drag, where react-use-gesture supports scroll, wheel, pinch and more.
