### ISSUE TITLE
Programatically set x position without breaking bounds 

### ISSUE THREAD

**Issue by cesarvarela** [react-spring/react-use-gesture#139]
I've been looking at this https://github.com/react-spring/react-use-gesture/issues/54, but also need the bounds prop and the rubber band to work, is it possible?

**Comment by dbismut** [comment]
Hi @cesarvarela, please make a sandbox with your best attempt and I’ll take it from there.

**Comment by cesarvarela** [comment]
Hi, here it is, the bounds functionally is mostly broken when doing the temp thing:

https://codesandbox.io/s/zen-leaf-jybic

thanks in advance!

**Comment by dbismut** [comment]
Several things:

- you’re linking to an old sandbox which uses react-use-gesture v5. Since then, `movement` has replaced `delta` (which is now the delta between two consecutive events). `temp` has also been relabeled `memo`.
- you’re not using the `bounds` or `rubberband` options in your sandbox
- the `initial` option is what you’re looking at if you need to alter the circle position outside the gesture.

**Comment by cesarvarela** [comment]
I've forked from an old sandbox but updated the dependencies

![image](https://user-images.githubusercontent.com/1172479/74876374-53f91080-5342-11ea-807a-7ea50fc1af98.png)

Also the bound option is there, maybe it showed you an old version?

**Comment by dbismut** [comment]
That’s possible I can see it now. Try removing the temp thing, use movement instead of delta, and add the initial option as explained in the docs. I’m on my phone so I can’t really help!

**Comment by cesarvarela** [comment]
Thanks! got it working https://codesandbox.io/s/zen-leaf-jybic

I saw the other issue about inertia, but is a bit involved, it would be nice to have an easier way.

**Comment by dbismut** [comment]
Great! Yeah inertia would be great. V9 has a lot on its plate atm so I’m not sure how easy it is to add an inertia at this point of time.
