### ISSUE TITLE
Why doc and examples are in beta?

### ISSUE THREAD

**Issue by sanjanind** [react-spring/react-use-gesture#159]
It's quite confusing. In production we only use stable version and while tried the example by changing it to a stable version nothing works without error.

Why ??? If you have drastic change then keep examples and docs in both versions. 

It's a big issue for the beginner. Can I get those examples in a stable version of both `react-spring` and  `react-use-gesture`

**Comment by dbismut** [comment]
Hi for a start. I’m sorry that your experience hasn’t been great, but this is not an airline company, you don’t get to complain with that  tone.

Developing is a rewarding experience but is also frustrating at times and I understand why you might be upset. However that’s not a reason to pass along your mood to others.

So rephrase your question and I’ll see what I can do.

**Comment by sanjanind** [comment]
@dbismut I'm working on the `6.0.10` version but while I referred the doc `https://use-gesture.netlify.com/docs/options` most of the things are not working. 

It will be helpful if I have the API doc version of the latest stable release. Else it is useless to spend time on this beta document. Most of these use cases are not backward compatible. 

I hope you understand the concern.

**Comment by joeshub** [comment]
While in my opinion documentation is probably one of the most important factors in adoption, I think the point @dbismut is making still stands here, in that the *mood passing* is not helpful in an open source setting, where developers are spending their free time to devote to building something for the entire community. I mean there’s always sending in a PR.

**Comment by dbismut** [comment]
@sanjanind 

1. You’re complaining about not using the latest stable version for `react-use-gesture`. **Latest version is v7**. I don’t have time to maintain documentation for all versions of this lib.

2. True, I’m using v9@next of react-spring in the docs because it doesn’t clutter the code as much as v8 and I thought would let the user focus on this lib rather than react-spring. 

3. I’ve explained this choice here: https://use-gesture.netlify.app/docs/introduction

4. Nothing justifies rudeness on GitHub. A lot of people are using this lib and some of them have reported serious breaking bugs that were indeed nerve-breaking without using your tone.

5. Since I do understand your concern I will make one introductory example with a react-spring v8 syntax.

**Comment by sanjanind** [comment]
@dbismut @joeshub Thanks for this great library, it helps a lot for me. Sorry if the voice is too rude.

As per my view, our doc should always point to the latest stable release with its example. And we should have another section like Try our Beta or something like that with all new changes with example. 😃 

anyways, I find it out from the old version on git. 

One Question If I use use-drag with use-spring then there will be any significant performance improvement?  (Only for image drag)

**Comment by dbismut** [comment]
Hi @sanjanind this. library. is. not. in. beta. the. docs. show. a. stable. release. this. library. is. not. react-spring.

I don't understand your question.
