### ISSUE TITLE
Wheel event does not expose clientX, clientY

### ISSUE THREAD

**Issue by jasco** [react-spring/react-use-gesture#204]
While evaluating to see if I could use this library, I noticed that the wheel event does not expose `clientX` and `clientY`.  I tried retrieving them from `event.nativeEvent` but I am seeing the following react warnings:

> Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

Is there interest in exposing this value?

**Comment by jasco** [comment]
While diving deeper I found the values of interest in the `event` object.  Using typescript I had to first cast it to a `React.WheelEvent`.

**Comment by dbismut** [comment]
The reason why you're seing the error has to do with accessing the event asynchronously. This happens when trying to fetch the last event which is debounced by the library (the only way to detect when wheel has ended). So you might want to do something along the lines of:

```js
if(!last) event.clientX
```

See here: https://use-gesture.netlify.app/docs/faq#accessing-source-event-triggers-a-warning-in-the-console
