### ISSUE TITLE
Not able to cancel onWheel

### ISSUE THREAD

**Issue by Fabiantjoeaon** [react-spring/react-use-gesture#86]
Hi there,

My page is navigated using a big 'carousel' on the vertical axis, it's possible to navigate using the mousewheel and using dragging, I have recreated it in a CodeSandbox: 

https://codesandbox.io/s/staging-bash-rge63. 

I set the Y position based on the current delta, and cancel the gesture and navigate to the next position after a certain threshold. This works as expected for dragging, however, when I use the onWheel event, the `cancel()` function doesn't seem to work. When logging `canceled`, it always returns false, and the gesture will continue, thus scrolling to the end of the page, when you just want to move one section.

Am I doing something wrong? I assume it has something to do with the `cancel` function..

**Comment by dbismut** [comment]
Hi @Fabiantjoeaon, I'll possibly clarify this in the docs but only drag and pinch gestures are cancelable. Since wheel has no start or end native handlers, there's no way to cancel it. You can have a look at this example that I think does what you're trying to achieve by attempting to detect wheel deceleration: https://codesandbox.io/s/react-use-gesture-wheel-clamp-urdco

**Comment by Fabiantjoeaon** [comment]
Ah okay, this wasn't clear to me indeed. Thanks, I'll have a look into it.
