### ISSUE TITLE
onWheel delta doesn't match event.delta?

### ISSUE THREAD

**Issue by mpolichette** [react-spring/react-use-gesture#96]
Hey,  I'm using `"react-use-gesture": "^6.0.7"` and I'm getting a weird behavior with `onWheel` and a stepped mouse, e.g. one which physically click between steps.

I first noticed, I was not getting any movement if i did a single step of the wheel.  Investigating, I defined the following handler: `useGesture({ onWheel: console.log })` and got the following event.
![Screen Shot 2019-10-11 at 2 37 29 PM](https://user-images.githubusercontent.com/2925660/66683478-c2132580-ec34-11e9-84d6-408182514128.png)

As you can see, the `event.deltaY` has a value, but the delta from `useGesture` is 0.  This isn't an issue if I scroll more quickly and get multiple events.

I've noticed this also effects my macbook trackpad w/ very small movements, but its harder to trigger a single event, so its less noticeable. 

Any thoughts on why the delta doesn't reflect the events or ideas for how I could recognize these small movements?

**Comment by dbismut** [comment]
@mpolichette hm this looks like a bug, thanks for reporting this, I’ll investigate this tomorrow.

**Comment by mpolichette** [comment]
Thanks @dbismut, you're a great maintainer! 👍

**Comment by dbismut** [comment]
@mpolichette thanks, that's good to hear! `6.0.8` is out and should fix this. It's actually a bigger issue than I initially thought, it actually applies to scroll as well and to `offset` and `movement` state attributes. I also did some refactoring so hopefully this doesn't break elsewhere!

**Comment by abepuentes** [comment]
@dbismut I'm pretty new to this stuff, so sorry if this is not the place to comment this. But I think after this change been applying since 6.0.8, the scroll movement has getting some "jiggle" behavior, because that's kind of difficult to explain, I was testing this example from drcmd (https://codesandbox.io/embed/react-three-fiber-suspense-gltf-loader-l900i ). If you change the version from 6.0.7 to any number above, the behavior change, and is very clear if you click on a seat becuase now the click move the model.

**Comment by dbismut** [comment]
@abepuentes Damn you're right. I though I could solve this in a minor release, but I'll release a cleaner `6.1.0` which might result in some minor breaking changes. Anyway `6.0.11` is released and should the issue with `previous`.

**Comment by abepuentes** [comment]
@dbismut 6.0.11 is working fine, I test it in my website and is ok. You are doing a great job.
